### ISSUE TITLE
Where should I place logo?

### ISSUE THREAD

**Issue by emrealparslan93** [SurveyLegend/hapi-docs#2]
Thanks for this beautiful library in advance!

I couldn't find which directory I should place my logo. I created /src/assets/images/logo.png path in my root directory, it didn't work. Can you help me with this?

**Comment by henrikdahl** [comment]
Thanks for your kind words! ✌️ 

`hapi-docs` is still in pre-release phase but we're preparing an actual full release fairly soon.

In this current version what you need to do is add your own templating. I will add an example of how such a project might look.

Do you merely want to change the logo or more of the design? I'll release a new version today that allows you to change the logo without having to download the entire src and template it yourself.

**Comment by emrealparslan93** [comment]
Thanks for quick reply @henrikdahl . I just want to add a logo, not the design. Design is awesome 👍 .
I dived into your code to find how to replace it, I tried to create folders such as `src`, `template` ...etc, but it didn't work. Btw, is there a reason you didn't publish `hapi-docs` in npm? Because I'm using npm and yarn is a manager I'm not experienced at 😄 .

**Comment by henrikdahl** [comment]
Glad you like it!

Basically what you do is copy the `src` folder from `hapi-docs` and then you need to reference your absolute path as mentioned in the `templatePath` in [plugin options](https://github.com/SurveyLegend/hapi-docs#plugin-options).

Then you'll have a local copy of the templating and be able to do whatever you want, such as replacing the logo ✌️

**Comment by henrikdahl** [comment]
Also, `hapi-docs` is published on npm. Yarn is a package manager that simply indexes npm. https://www.npmjs.com/package/@surveylegend/hapi-docs

**Comment by emrealparslan93** [comment]
@henrikdahl I have copied `src` folder to my project root and reference it in `hapi-docs` options. I couldn't get it work.

Here is my project hierarchy:

```
- config
-- hapi-docs.conf.js
-- manifest.conf.js
- src
- index.js
```

Here is my `hapi-docs.conf.js`:

`module.exports = {
  basePath: "/v1",
  templatePath: "/src",
  pathPrefixSize: 2
  ...
};
`

**Comment by emrealparslan93** [comment]
I tried `__dirname` to get absolute path but it also gives me 403 when I try to open `/docs` page.

`templatePath: __dirname + "../src"`

**Comment by henrikdahl** [comment]
Do you have Slack? I think it would be faster to continue this discussion over there ✌️ 

https://join.slack.com/t/hapihour/shared_invite/enQtNTA5MDUzOTAzOTU4LTUyZmFiYjkyMTBmNDcyMmI2MmRjMzg4Y2YzNTlmNzUzNjViN2U1NmYyY2NjYjhiYWU4MGE2OTFhZDRlYWMyZDY

**Comment by emrealparslan93** [comment]
@henrikdahl helped me a lot about this issue. Next release will include this feature as plugin option. So I'm closing this issue.
