### ISSUE TITLE
Code Examples & Example Response

### ISSUE THREAD

**Issue by emrealparslan93** [SurveyLegend/hapi-docs#3]
How can I generate code examples and example responses?

**Comment by henrikdahl** [comment]
Guide coming with a new release soon ✌️

**Comment by mengdodo** [comment]
this ui is very beautiful , the same as https://github.com/lord/slate

**Comment by antony** [comment]
Also stuck on this :)

I can't see in the example how code examples or languages are enabled. Is the heroku app using an older version of the example/plugin?

**Comment by antony** [comment]
For anybody else who stumbles across this - check out this repository, make your template changes, then copy the `dist` dir to wherever you want to point `templateDir`.

**Comment by kahluagenie** [comment]
@antony good advice, thanks! 
To add on to that, if your examples are a part of route data, you can modify `path.js` to pull that data from additional fields. For example,
`examples: Hoek.reach(routeOptions, 'examples') || null`

And use that field in the template. You will then have to fork and publish the module under your own name/org or point to a git repo.
