### ISSUE TITLE
Migrate to @hapi

### ISSUE THREAD

**Issue by Nargonath** [SurveyLegend/hapi-docs#4]
The hapi ecosystem migrated to scoped packages a few days ago and all the other packages have been deprecated. I think your dependencies needs to be updated.

If I have some time this weekend I'll try to put up a PR.

**Comment by igauravsehrawat** [comment]
@Nargonath Are using using still `hapi-docs`? or moved on?

**Comment by Nargonath** [comment]
I'm not currently using it. I couldn't make it work on my current project. If you want to make the PR, go for it. 😃

**Comment by antony** [comment]
In case it's useful - https://github.com/SurveyLegend/hapi-docs/pull/24

Not sure who is maintaining this library any more - ping @henrikdahl for more info - is there a plan for further improvement or should we be making a fork?

**Comment by henrikruscon** [comment]
Sorry for the lack of maintenance on `hapi-docs`, we initially had big plans and intended to support it fully. However, we unfortunately had to put our focus elsewhere in our product and with such a small team it meant `hapi-docs` stagnated.

Thanks for showing interest however, closing this and we will further on try to maintain the project better.
