### ISSUE TITLE
Validation documentation isn't comprehensive

### ISSUE THREAD

**Issue by antony** [SurveyLegend/hapi-docs#7]
It seems that the documentation generator ignores important items such as:

- [ ]  Nested object documentation
- [ ]  Conditionals like Joi.when
- [ ]  Min + Max on arrays
- [ ]  String sizes
- [x]  Nested array items
- [x] Restricted inputs (Joi.only())

Would be great to support these!

**Comment by henrikruscon** [comment]
Thank you for the contribution, next release will cover these.
