### ISSUE TITLE
Ability to document miscellaneous information

### ISSUE THREAD

**Issue by antony** [SurveyLegend/hapi-docs#9]
It would be very useful if there was a way to document "extra information", such as how to build CDN urls, for example.

I would suggest this is added much like errors, auth, etc, as an array of optional pages which could be inserted into the docs, i.e:

```js
{ plugin: HapiDocs,
      options: {
        pages: [
          {
            name: 'CDN Urls',
            title: 'Some page title here'
            descriptions: [
              "Some different pararaphs go here",
              "Relating to the subject matter"
            ]
          }
        ],
        ...
      }
}
```

**Comment by henrikruscon** [comment]
This will be part of next release and documented by then. Thanks for the suggestion!
